### ISSUE TITLE
BUG - crashing studio while trying to open object`

### ISSUE THREAD

**Issue by Khalsa-jio** [winteragency/sanity-plugin-link-field#5]
Hello,

I appreciate your efforts! However, I've encountered a few issues while using this plugin and thought it would be beneficial to bring one to your attention.

Here's how you can reproduce the issue:

Without selecting any type, click on the toggle button. After doing so, I consistently receive an error when attempting to reopen it.<img width="1132" alt="Screenshot 2024-04-20 at 5 13 18 PM" src="https://github.com/winteragency/sanity-plugin-link-field/assets/68214394/673bae70-3e97-4667-8f25-3266ab7a7afe">

**Comment by Khalsa-jio** [comment]
@marcusforsberg  - Hi mate, I also found currently blank field doesn't show when selecting internal and also seems need to add blank field in LinkValue type...

**Comment by marcusforsberg** [comment]
@Khalsa-jio Thanks for the heads-up! The crash and the missing "blank" field were caused by the same issue and the fix was just pushed in v1.1.1. Please give it a go and let me know if it works better for you now.

The `blank` property is not available in the `LinkValue` type itself since it's not relevant for all field types; specifically "phone" and "email" links do not have the "blank" option at all. The `blank` type is available on the `InternalLink`, `ExternalLink` and `CustomLink` types. There are type guards available to check the type of link you're dealing with: `isInternalLink`, `isExternalLink`, `isEmailLink`, `isPhoneLink` and `isCustomLink`.

**Comment by Khalsa-jio** [comment]
thanks for clearing this out, I will try it and will update you if I find any other issue with it, thanks

**Comment by Khalsa-jio** [comment]
Also I was thinking it would be good to add another option for File type link, please let me know if you would like me to do something related to it, thanks
